### ISSUE TITLE
solution for FASHION.py

### ISSUE THREAD

**Issue by praserocking** [shiv6146/SPOJ#1]
Does that Really pass all the testcases? I was just looking through the solutions and found that you are not sorting the list you get as input and calculate the hotness directly!

Just curious whether the solution actually works!
:8ball:

**Comment by shiv6146** [comment]
Yeah dude it has been accepted. Just now checked my SPOJ acc. These were the solutions which I submitted when I started learning Python. So, please do pardon me as there might be a lot of inefficiencies :P
![selection_045](https://cloud.githubusercontent.com/assets/5592146/14842260/1e640fda-0c63-11e6-87c5-c0d81c17f471.png)

**Comment by praserocking** [comment]
think i should revisit the problem statement again :-P
